/* gate-check
runs: both
subject: shared-environment
cost: seconds
ciIdentity: ci-presence
why: >-
  the live store's mirror of `stories/**` (ADR-0445 D1) is regenerated by whichever PR last merged,
  so a sibling's landing moves it under this branch — the same shared-live-state reason as
  check:guidance. It fails LOUDLY on a stale mirror rather than falling back to disk, because a
  fallback would report health while a reader is served the stale tree (ADR-0302's lesson)
*/
import path from "node:path";
import { fileURLToPath } from "node:url";

import { projectWorkHierarchy } from "@storytree/drive";
import { REPO_ROOT_ENV, resolveRepoRoot, type WorkHierarchySnapshot } from "@storytree/library";
import { closePool, createPool, PgWorkHierarchyStore } from "@storytree/library/store";

import { judgeHierarchyDrift, type HierarchyDriftInputs } from "./hierarchy-drift.js";
import {
  commitShaOf,
  committedAt,
  resolveBaseRef,
  storiesDirty,
  storiesTreeSha,
} from "./hierarchy-git.js";

/**
 * `pnpm check:hierarchy-drift` — the thin I/O SHELL over {@link judgeHierarchyDrift}.
 *
 * The gatherer/judge split every other rung here uses: this module reads the store, reads git,
 * prints, and sets an exit code; every rule lives in the pure judge next door and is unit-tested
 * against literals with no store and no filesystem.
 *
 * ## IT FAILS LOUDLY, AND NEVER FALLS BACK TO DISK
 *
 * That is the increment's own fence, and ADR-0302's whole lesson: a check that answers from the
 * source when the mirror is unreadable reports health while something else is being served the
 * stale thing. There is no fallback branch in this file. An unopenable store, an unreadable base
 * ref, an empty projection, a schema-version gap and a genuine content disagreement are all
 * FAILURES that name their own remedy — never skips, and never a green that examined nothing.
 *
 * ## IT IS `shared-environment` ON THE GATE'S ORDERING AXES
 *
 * The mirror is regenerated by whichever PR last merged, so a sibling's landing can move it under
 * this branch. Like `check:guidance` and `check:adr-health` it therefore runs AFTER both expensive
 * legs — a red here may be nobody's fault on this diff, and it must not precede the session's own
 * answer.
 *
 * ## WHY THIS RUNG IS WORTH ITS PLACE BEFORE ANY READER USES THE MIRROR
 *
 * No reader has been switched onto the projection yet — `readTree` is untouched and inc-03 owns the
 * switch. A projection nothing reads and nothing checks would freeze silently and be discovered by
 * the increment that switches the readers over, which is the worst possible moment. The rung is what
 * keeps the mirror honest during the interval it is unused.
 */

const EXIT_FAIL = 1;

const repoRoot = (): string =>
  resolveRepoRoot({
    env: process.env[REPO_ROOT_ENV],
    derived: fileURLToPath(new URL("../../../", import.meta.url)),
  }).root;

/**
 * The two ways this store can refuse the read for a reason that is about the DATABASE rather than
 * about the mirror — each with its own repair, which is why they are told apart rather than folded.
 *
 * `42P01` the DDL has never been applied here; `42501` the connecting identity has no grant. Both
 * are FAILURES: the mirror was never read, so nothing about it was judged. Neither is ever a skip.
 */
function pgErrorCode(err: unknown): string | undefined {
  const code = (err as { code?: unknown } | null)?.code;
  return typeof code === "string" ? code : undefined;
}

function isMissingRelation(err: unknown): boolean {
  return pgErrorCode(err) === "42P01" || /relation .* does not exist/i.test(String(err));
}

function isPermissionDenied(err: unknown): boolean {
  return pgErrorCode(err) === "42501" || /permission denied for (table|relation)/i.test(String(err));
}

async function main(): Promise<number> {
  const root = repoRoot();
  const baseRef = resolveBaseRef();

  let handle: Awaited<ReturnType<typeof createPool>> | undefined;
  try {
    handle = await createPool();
  } catch (err) {
    process.stdout.write(
      "✗ check:hierarchy-drift — the live store could not be opened:\n" +
        `  ${err instanceof Error ? err.message : String(err)}\n\n` +
        "  This is a FAILURE, not a skip: the mirror was never read, so nothing about it was\n" +
        "  judged. Bring the DB up (pnpm db:up) and re-run.\n",
    );
    return EXIT_FAIL;
  }

  try {
    let stored: WorkHierarchySnapshot | null;
    try {
      stored = await new PgWorkHierarchyStore(handle.pool).readSnapshot();
    } catch (err) {
      if (isPermissionDenied(err)) {
        // The tables exist; this identity may not read them. In CI that means the ADR-0451 grants
        // have not been applied to this database — a one-command owner-run repair, and NOT something
        // a re-run or a wider `catch` should paper over.
        process.stdout.write(
          "✗ check:hierarchy-drift — permission denied on the work-hierarchy tables.\n\n" +
            `  ${err instanceof Error ? err.message : String(err)}\n\n` +
            "  The tables are here; this identity has no grant on them. The mirror was never read,\n" +
            "  so nothing about it was judged — a FAILURE, never a skip. Apply the grants as the\n" +
            "  schema owner (ADR-0451 D4), from the repo root:\n\n" +
            "    STORYTREE_DB_USER=<owner> npx tsx infra/apply-ci-presence-grants.ts\n",
        );
        return EXIT_FAIL;
      }
      if (!isMissingRelation(err)) throw err;
      // The tables are not in THIS database yet. Distinct from "loaded nothing", and it has its own
      // remedy: the loader applies the DDL, so one run creates the relations and fills them.
      process.stdout.write(
        "✗ check:hierarchy-drift — the work-hierarchy tables are not in this database.\n\n" +
          "  `applySchema` is not run by ordinary `--pg` commands, so a database that has not seen\n" +
          "  a load (or a `pnpm db:schema --write`) since these tables landed does not have them. The\n" +
          "  loader applies the DDL itself:\n\n" +
          "    pnpm hierarchy:load\n",
      );
      return EXIT_FAIL;
    }

    const dirty = storiesDirty(root);
    const inputs: HierarchyDriftInputs = {
      stored,
      // Projecting this checkout is cheap and total, so it is always done: the judge decides whether
      // the comparison is MEANINGFUL, and it can only say `not-compared` honestly if it was handed
      // something to not compare.
      checkout: projectWorkHierarchy(path.join(root, "stories"), {
        commitSha: commitShaOf(root, "HEAD") ?? "unknown",
        storiesTreeSha: storiesTreeSha(root, "HEAD") ?? "unknown",
        generatedAt: new Date().toISOString(),
        generator: "check:hierarchy-drift",
      }),
      baseRef,
      baseStoriesTreeSha: storiesTreeSha(root, baseRef),
      baseCommittedAt: committedAt(root, baseRef),
      headStoriesTreeSha: storiesTreeSha(root, "HEAD"),
      // git could not answer ⇒ treat as dirty. Fail-closed: an unknown working tree must not license
      // a comparison whose premise is that the working tree is exactly the mirrored one.
      storiesDirty: dirty !== false,
    };

    const verdict = judgeHierarchyDrift(inputs);
    for (const line of verdict.lines) process.stdout.write(`${line}\n`);
    return verdict.ok ? 0 : EXIT_FAIL;
  } finally {
    await closePool(handle.pool, handle.connector);
  }
}

process.exitCode = await main();
