import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { GATE_SKIP_EXIT_CODE } from "./gate-runner.js";
import {
  CORE_PACKAGE,
  ENGINE_DIR,
  ENGINE_PACKAGES,
  R3F_PACKAGE,
  bannerFor,
  computeSyncPlan,
  detectEngineDrift,
  isEngineSource,
  judgeEngineCheck,
  normalizeEol,
  rewriteImports,
  syncedContent,
} from "./web-engine-sync.js";

// A tiny stand-in core: two source files + a test file + a non-ts file. Only the two
// sources are engine sources; the rest must be filtered out of the plan.
const CORE = new Map<string, string>([
  ["rng.ts", "export const hash = (s: string): number => s.length;\n"],
  ["scene.ts", "import { hash } from './rng.js';\nexport const buildScene = () => hash('x');\n"],
  ["scene.test.ts", "import { test } from 'node:test';\ntest('x', () => {});\n"],
  ["README.md", "# not synced\n"],
]);

test("isEngineSource keeps browser sources, drops tests / decls / non-ts", () => {
  assert.equal(isEngineSource("scene.ts"), true);
  assert.equal(isEngineSource("index.ts"), true);
  assert.equal(isEngineSource("scene.test.ts"), false);
  assert.equal(isEngineSource("scene.d.ts"), false);
  assert.equal(isEngineSource("README.md"), false);
  // A shared test fixture extracted OUT of a `.test.ts` so two suites can use it is
  // still test scaffolding: dead data in the public bundle if synced. Naming differs
  // from `.test.ts`; nature does not.
  assert.equal(isEngineSource("scene-fixture.ts"), false);
  assert.equal(isEngineSource("scene-fixture.tsx"), false);
  // The drop is by SUFFIX, so a production module that merely mentions the word is kept.
  assert.equal(isEngineSource("fixture-loader.ts"), true);
});

// THE PROPERTY THAT MAKES THE `-fixture.ts` DROP SAFE, asserted against the REAL tree
// rather than assumed: a dropped file is absent from the web bundle, so if any file we
// DO sync imported one, the site would fail to resolve it at build time. `.test.ts` has
// always been safe by construction (nothing production imports a test); `-fixture.ts` is
// only safe by discipline, so the discipline is pinned here.
//
// Deliberately a real-repo read, not an in-memory fixture: an in-memory case would prove
// the assertion's shape and nothing about this repo, which is the whole point.
test("no SYNCED engine source imports a `-fixture` module", () => {
  const repoRoot = path.resolve(fileURLToPath(import.meta.url), "..", "..", "..", "..");
  const offenders: string[] = [];
  let scanned = 0;

  for (const pkg of ENGINE_PACKAGES) {
    const srcDir = path.join(repoRoot, ...pkg.srcDir.split("/"));
    let files: string[];
    try {
      files = readdirSync(srcDir);
    } catch {
      continue; // package not present in this checkout — the sync gate reports that itself
    }
    for (const file of files.filter(isEngineSource)) {
      scanned += 1;
      const source = readFileSync(path.join(srcDir, file), "utf8");
      if (/from\s+["'][^"']*-fixture(?:\.js)?["']/.test(source)) {
        offenders.push(`${pkg.srcDir}/${file}`);
      }
    }
  }

  // Non-vacuity: if this ever scans nothing, the assertion below is free and would
  // silently stop meaning anything — the failure mode this whole arc exists to fence.
  assert.ok(scanned > 0, "scanned no engine sources — the guard would be vacuous");
  assert.deepEqual(
    offenders,
    [],
    "a synced engine source imports a `-fixture` module, which is dropped from the web bundle — " +
      "move the shared data into a synced module, or stop syncing the importer",
  );
});

test("computeSyncPlan syncs only engine sources, stamped + sorted under ENGINE_DIR", () => {
  const plan = computeSyncPlan(CORE);
  assert.deepEqual(
    plan.map((p) => p.file),
    ["rng.ts", "scene.ts"], // .test.ts + .md filtered, sorted
  );
  assert.deepEqual(
    plan.map((p) => p.path),
    [`${ENGINE_DIR}/rng.ts`, `${ENGINE_DIR}/scene.ts`],
  );
  // Each synced file is the @generated banner followed by the source, with relative
  // imports made extensionless for Vite (`./rng.js` → `./rng`).
  const scene = plan.find((p) => p.file === "scene.ts")!;
  assert.ok(scene.content.startsWith(bannerFor("scene.ts")));
  assert.ok(scene.content.includes("export const buildScene"));
  assert.match(scene.content, /@generated by `pnpm sync:web-engine`/);
  assert.match(scene.content, /DO NOT EDIT/);
  assert.match(scene.content, /from '\.\/rng'/); // .js stripped
  assert.ok(!scene.content.includes("'./rng.js'"));
});

test("rewriteImports strips .js from relative specifiers only", () => {
  assert.equal(rewriteImports("import { x } from './rng.js';"), "import { x } from './rng';");
  assert.equal(rewriteImports('export { y } from "../hex.js";'), 'export { y } from "../hex";');
  assert.equal(rewriteImports("import type { Pt } from './hex.js';"), "import type { Pt } from './hex';");
  // bare specifiers + non-.js relative paths are untouched
  assert.equal(rewriteImports("import a from 'node:fs';"), "import a from 'node:fs';");
  assert.equal(rewriteImports("import d from './data.json';"), "import d from './data.json';");
});

test("detectEngineDrift passes when the synced copy matches the plan", () => {
  const plan = computeSyncPlan(CORE);
  const synced = new Map(plan.map((p) => [p.file, p.content]));
  const problems = detectEngineDrift(
    plan,
    (f) => synced.get(f) ?? null,
    [...synced.keys()],
  );
  assert.deepEqual(problems, []);
});

test("detectEngineDrift flags a missing synced file", () => {
  const plan = computeSyncPlan(CORE);
  const problems = detectEngineDrift(plan, (f) => (f === "rng.ts" ? syncedContent("rng.ts", CORE.get("rng.ts")!) : null), ["rng.ts"]);
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "scene.ts");
  assert.match(problems[0]!.reason, /missing/);
});

test("detectEngineDrift flags a stale (content-drifted) synced file", () => {
  const plan = computeSyncPlan(CORE);
  const synced = new Map(plan.map((p) => [p.file, p.content]));
  synced.set("scene.ts", synced.get("scene.ts")! + "// a hand edit that drifted\n");
  const problems = detectEngineDrift(plan, (f) => synced.get(f) ?? null, [...synced.keys()]);
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "scene.ts");
  assert.match(problems[0]!.reason, /STALE/);
});

test("detectEngineDrift is EOL-insensitive — a CRLF checkout is not drift", () => {
  const plan = computeSyncPlan(CORE);
  const synced = new Map(plan.map((p) => [p.file, p.content.replace(/\n/g, "\r\n")]));
  const problems = detectEngineDrift(plan, (f) => synced.get(f) ?? null, [...synced.keys()]);
  assert.deepEqual(problems, []);
});

test("detectEngineDrift flags a stale leftover no longer in the core", () => {
  const plan = computeSyncPlan(CORE);
  const synced = new Map(plan.map((p) => [p.file, p.content]));
  synced.set("removed.ts", "// a core file that was deleted upstream\n");
  const problems = detectEngineDrift(plan, (f) => synced.get(f) ?? null, [...synced.keys()]);
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "removed.ts");
  assert.match(problems[0]!.reason, /no longer in the core/);
});

test("normalizeEol collapses CRLF to LF", () => {
  assert.equal(normalizeEol("a\r\nb\r\n"), "a\nb\n");
});

// ── The web-experience-sync generalisation (ADR-0123): one mechanism, two packages ──
// Contract-id-led tests (ADR-0122): each `wes-…` id below is a declared contract of the
// capability; `storytree coverage web-experience-sync` credits them by name.

/** R3F-style fixture: a .tsx component + an index barrel + a .test.tsx that must be filtered. */
const R3F_CORE = new Map<string, string>([
  ["Mapper.tsx", "import { Scene } from '@storytree/forest-world';\nexport const Mapper = () => null;\n"],
  ["index.tsx", "export { Mapper } from './Mapper.js';\n"],
  ["Mapper.test.tsx", "// excluded test file\n"],
]);

test("wes-tsx-is-engine-source: .tsx is engine source; .test.ts / .test.tsx / .d.ts never are", () => {
  assert.equal(isEngineSource("Mapper.tsx"), true);
  assert.equal(isEngineSource("index.tsx"), true);
  assert.equal(isEngineSource("Mapper.test.tsx"), false); // invariant: .test.tsx stays excluded
  assert.equal(isEngineSource("x.test.ts"), false);
  assert.equal(isEngineSource("x.d.ts"), false);
  // …and through the plan: the component layer syncs, its tests never do.
  const plan = computeSyncPlan(R3F_CORE, R3F_PACKAGE);
  assert.deepEqual(plan.map((p) => p.file), ["Mapper.tsx", "index.tsx"]);
});

test("wes-second-package-plans-beside-the-core: r3f files land under src/lib/forest-world-r3f with r3f-naming banners while the core plan stays byte-identical to the single-package era", () => {
  const r3fPlan = computeSyncPlan(R3F_CORE, R3F_PACKAGE);
  assert.deepEqual(
    r3fPlan.map((p) => p.path),
    ["src/lib/forest-world-r3f/Mapper.tsx", "src/lib/forest-world-r3f/index.tsx"],
  );
  const mapper = r3fPlan.find((p) => p.file === "Mapper.tsx")!;
  assert.ok(mapper.content.startsWith(bannerFor("Mapper.tsx", R3F_PACKAGE)));
  assert.match(mapper.content, /Synced from packages\/forest-world-r3f\/src\/Mapper\.tsx/);
  assert.ok(!mapper.content.includes("packages/forest-world/src/")); // never the core's path

  // The core's plan is BYTE-IDENTICAL to the single-package era: same dest paths, and
  // the exact banner bytes pinned literally — churn here would red the live drift gate
  // over the already-synced site copy.
  const corePlan = computeSyncPlan(CORE);
  assert.deepEqual(
    corePlan.map((p) => p.path),
    [`${ENGINE_DIR}/rng.ts`, `${ENGINE_DIR}/scene.ts`],
  );
  assert.equal(
    bannerFor("scene.ts"),
    "// @generated by `pnpm sync:web-engine` — DO NOT EDIT THIS COPY.\n" +
      "// Synced from packages/forest-world/src/scene.ts in the storytree parent repo (the\n" +
      "// shared forest-world render core, ADR-0093). Edit the core there and re-sync; a\n" +
      "// stale copy fails the parent's `check:web-engine` gate.\n\n",
  );
  assert.deepEqual(computeSyncPlan(CORE, CORE_PACKAGE), corePlan); // explicit core pkg ≡ default
});

test("wes-core-import-rewrites-to-sibling: @storytree/forest-world import specifiers rewrite to ../forest-world; any other @storytree/* import fails the plan loudly; comment mentions are untouched", () => {
  const core = new Map([
    [
      "Mapper.tsx",
      "import { Scene } from '@storytree/forest-world';\n" +
        'import type { SceneG } from "@storytree/forest-world";\n' +
        "export const Mapper = () => null;\n",
    ],
  ]);
  const plan = computeSyncPlan(core, R3F_PACKAGE);
  assert.equal(plan.length, 1, "Mapper.tsx must appear in the sync plan");
  const { content } = plan[0]!;
  assert.ok(
    !content.includes("@storytree/forest-world"),
    "workspace specifier must be rewritten in the synced copy",
  );
  assert.ok(content.includes("from '../forest-world'"), "static import rewrites to the sibling dir");
  assert.ok(content.includes('from "../forest-world"'), "type-only import rewrites too");

  // The no-smuggling wall: any OTHER workspace import is a plan-time error naming the specifier.
  const badCore = new Map([["Mapper.tsx", "import { x } from '@storytree/library';\n"]]);
  assert.throws(
    () => computeSyncPlan(badCore, R3F_PACKAGE),
    (err: unknown) => {
      assert.ok(err instanceof Error, "must throw an Error");
      assert.match(err.message, /@storytree\/library/i);
      return true;
    },
  );

  // COMMENT mentions are not specifiers: the real core names workspace packages in prose
  // (packages/forest-world/src/index.ts:1, scene.ts:193) — a comment must neither rewrite
  // (churning the synced core bytes) nor throw (crashing the core's own sync).
  const commented = new Map([
    [
      "index.ts",
      "// @storytree/forest-world — the shared render core (mirrors @storytree/drive's shape)\n" +
        "export const x = 1;\n",
    ],
  ]);
  const [idx] = computeSyncPlan(commented);
  assert.ok(idx!.content.includes("// @storytree/forest-world — the shared render core"));
  assert.ok(!idx!.content.includes("// ../forest-world"));
});

test("wes-drift-covers-both-dirs: modified / missing / stale-leftover files in EITHER synced dir red the one gate with the file named; a faithful two-dir state is green", () => {
  const corePlan = computeSyncPlan(CORE);
  const r3fPlan = computeSyncPlan(R3F_CORE, R3F_PACKAGE);
  const coreSynced = new Map(corePlan.map((p) => [p.file, p.content]));
  const r3fSynced = new Map(r3fPlan.map((p) => [p.file, p.content]));
  // The shell composes exactly this: ONE check spanning every synced package dir.
  const driftBoth = () => [
    ...detectEngineDrift(corePlan, (f) => coreSynced.get(f) ?? null, [...coreSynced.keys()]),
    ...detectEngineDrift(r3fPlan, (f) => r3fSynced.get(f) ?? null, [...r3fSynced.keys()]),
  ];

  // Faithful two-dir state: green.
  assert.deepEqual(driftBoth(), []);

  // (a) a MODIFIED file in the r3f dir while the core stays faithful.
  r3fSynced.set("Mapper.tsx", r3fSynced.get("Mapper.tsx")! + "// a hand edit\n");
  let problems = driftBoth();
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "Mapper.tsx");
  assert.match(problems[0]!.reason, /STALE/);
  r3fSynced.set("Mapper.tsx", r3fPlan.find((p) => p.file === "Mapper.tsx")!.content);

  // (b) a MISSING file in the r3f dir.
  r3fSynced.delete("index.tsx");
  problems = driftBoth();
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "index.tsx");
  assert.match(problems[0]!.reason, /missing/);
  r3fSynced.set("index.tsx", r3fPlan.find((p) => p.file === "index.tsx")!.content);

  // (c) a STALE .tsx LEFTOVER in the r3f dir (deleted upstream, its copy left behind).
  r3fSynced.set("Old.tsx", "// stale leftover R3F component\n");
  problems = driftBoth();
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "Old.tsx");
  assert.match(problems[0]!.reason, /no longer in the core/);
  r3fSynced.delete("Old.tsx");

  // …and a CORE-dir drift reds through the same composed gate (either dir, one gate).
  coreSynced.delete("scene.ts");
  problems = driftBoth();
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "scene.ts");
  assert.match(problems[0]!.reason, /missing/);
});

// ---------- the verdict: a run that compared nothing may not claim a pass ----------
//
// THE RED ANCHOR for `gate-self-report-honesty-arc-inc-01`. Both branches below returned 0 before
// this, and `gate-run.ts` computes each row of its per-step table from the exit code — so the gate
// printed PASS for a step that read no file, on every checkout without the `web/` submodule, while
// its two siblings over the identical state printed SKIP and forced `GATE GREEN, NARROWED`.
// `judgeEngineCheck` is asserted to return a NON-ok status on each, which is the property; the
// exit-code mapping it feeds is the shell's, and `gate-order.test.ts` separately holds the root
// script to an invocation form that does not collapse a 3 into a 1.

test("a missing web/ checkout is a declared SKIP locally, and a hard failure in CI", () => {
  const local = judgeEngineCheck({ kind: "no-web-checkout" }, { inCi: false });
  assert.equal(local.status, "skip", "locally the submodule is opt-in — this is not a pass");
  assert.match(local.message, /SKIP/);
  assert.match(local.message, /git submodule update --init web/, "it names the remedy");

  const ci = judgeEngineCheck({ kind: "no-web-checkout" }, { inCi: true });
  assert.equal(ci.status, "fail", "in CI the workflow must clone the pinned SHA first");
  assert.match(ci.message, /CI/);
});

test("a checkout in which NO package has been adopted declares a SKIP locally", () => {
  // The per-package bootstrap allowance is not an environment fault — it stays legitimate in CI —
  // so unlike the branch above it never becomes a failure.
  const verdict = judgeEngineCheck({ kind: "no-adopted-package" }, { inCi: false });
  assert.equal(verdict.status, "skip", "nothing was compared, so it is not a pass");
  assert.match(verdict.message, /SKIP/);
  assert.match(verdict.message, /nothing was compared/, "it says what it did not do");
});

test("the bootstrap state withholds the SKIP CODE in CI, but never the fact", () => {
  // This is the ONE blind branch reachable in CI (the workflow clones web/ or fails, so the
  // absent-checkout branch cannot fire there). CI runs this script through `pnpm gate --ci`, which
  // counts a skip as a failure (ADR-0606 D3) — so emitting GATE_SKIP_EXIT_CODE would
  // convert a declared skip into a hard red, this arc's own defect with the sign flipped. What may
  // NOT be withheld is the statement that nothing was compared.
  const ci = judgeEngineCheck({ kind: "no-adopted-package" }, { inCi: true });
  assert.equal(ci.status, "ok", "a legitimate bootstrap state must not red CI");
  assert.match(ci.message, /NOTHING TO COMPARE/, "the CI log still says it compared nothing");
  assert.match(ci.message, /nothing was compared/);

  // …and the local run still declares the skip, so the gate's table is unaffected by the carve-out.
  assert.equal(judgeEngineCheck({ kind: "no-adopted-package" }, { inCi: false }).status, "skip");
});

test("only a run that actually compared a dir reports OK", () => {
  const verdict = judgeEngineCheck(
    { kind: "compared", files: 7, dirs: [CORE_PACKAGE.destDir] },
    { inCi: false },
  );
  assert.equal(verdict.status, "ok");
  assert.match(verdict.message, /OK: 7 synced file\(s\)/);
  assert.match(verdict.message, new RegExp(CORE_PACKAGE.destDir.replace(/\//g, "\\/")));
});

test("no blind branch reports a plain OK to the gate runner — the property the table is read through", () => {
  // Exhaustive over the two sights that compare nothing, in the environment whose runner reads the
  // per-step table. A future branch that returns `ok` without comparing has to break this to land.
  for (const kind of ["no-web-checkout", "no-adopted-package"] as const) {
    const verdict = judgeEngineCheck({ kind }, { inCi: false });
    assert.notEqual(verdict.status, "ok", `${kind} compared nothing`);
  }
  // In CI the one reachable blind branch keeps a zero exit (see above), so the property that holds
  // there is the weaker but still load-bearing one: it never claims to have compared anything.
  const ci = judgeEngineCheck({ kind: "no-adopted-package" }, { inCi: true });
  assert.doesNotMatch(ci.message, /\bOK:/, "no CI branch prints the pass banner over an empty run");

  // …and the code the shell maps a skip onto is the one the runner reads as SKIP, not as a pass.
  assert.notEqual(GATE_SKIP_EXIT_CODE, 0);
});
